// Server-side copy of the social offers data (Excel-Tabelle)
// Used by the chat tool `search_offers` to look up matching entries.
export interface OfferEntry {
  id: number;
  name: string;
  category?: string;
  address?: string;
  description?: string;
  phone?: string;
  email?: string;
  openingHours?: string;
}

export const offers: OfferEntry[] = [
  { id: 1, name: "Tetenshof", category: "Freizeit", address: "Westerheverstr. 6, 25836 Osterhever, OT Alt-Augustenkoog", phone: "Beate Tetens Tel. 0 48 65 / 6 96" },
  { id: 2, name: "Angelsportverein Drage e.V.", category: "Freizeit", address: "Deichweg 6c 25878 Drage", phone: "+49 160 99188978", email: "vorstand@asv-drage.de" },
  { id: 3, name: "Seeth/Drager Speeldeel Theatergruppe", category: "Freizeit", address: "Drage", phone: "Heinke Dirks Seeth  – Tel. 04881 / 7619 Maren Fürst - Tel.04881/1504" },
  { id: 4, name: "Seeth Ringreiterverein", category: "Sportverein", address: "Königsberger Str. 24     25876 Schwabstedt", phone: "Nico Kindt  +49 1747430517" },
  { id: 5, name: "Eider-Treene-Schule Friedrichstadt", category: "Schule", address: "Schleswiger Straße 29 Schleswiger Straße 29", phone: "04881-651", email: "eider-treene-schule.toenning@schule.landsh.de" },
  { id: 6, name: "Grundschule in Friedrichstadt  an der Treene", category: "Schule", address: "Ostdeutsche Str. 3    25840 Friedrichstadt", phone: "04881 / 930420", email: "schule-an-der-treene.friedrichstadt@schule.landsh.de" },
  { id: 7, name: "Dänsche Schule Friedrichstadt (Hans Helgesen-Skolen)", category: "Schule", address: "Schleswiger Straße 23   25840 Friedrichstadt", phone: "04881 261", email: "hhs@skoleforeningen.de" },
  { id: 8, name: "ADS-Kita Brückenstraße Friedrichstadt", category: "Kita", address: "Brückenstraße 21, 25840 Friedrichstadt", phone: "04881 7340", email: "ads-kita-brueckenstrasse@dein-ads.de", openingHours: "von 07:30 Uhr  bis 12:30 Uhr" },
  { id: 9, name: "ADS-Krippenhaus Doesburger Straße", category: "Kita / Krippe", address: "Doesburger Straße 27   25840 Friedrichstadt", phone: "04 881 - 93 87 337", email: "ads-kita-doesburgerstrasse@dein-ads.de", openingHours: "07:00 - 16:00 Uhr" },
  { id: 10, name: "ADS-Kita Großer Garten", category: "Kita", address: "Großer Garten 7  25840 Friedrichstadt", phone: "04 881 - 87 66 18", email: "ads-kita-grosser-garten@dein-ads.de", openingHours: "07:00 - 16:00" },
  { id: 11, name: "Dänische Kindertagesstätte - Friedrichstadt", category: "Kita", address: "Treenesiedlung 15   25840 Friedrichstadt", phone: "04881/467", email: "Frederiksstad_boernhave@skoleforeningen.de" },
  { id: 12, name: "Jugendzentrum Friedrichstadt", category: "Jugendzentrum", address: "Am Mittelburgwall 40    25840 Friedrichstadt", phone: "0 48 81 / 93 77 79", email: "jugend@ev-kirche-friedrichstadt.de", openingHours: "Mo/Di/Do/Fr 14 bis 20 Uhr und Mi 18 bis 20 Uhr" },
  { id: 13, name: "Müttterfrühstück Friedrichstadt", category: "Mütterfrühstück", address: "Am Mittelburgwall 40 25840 Friedrichstadt", phone: "04861-6175718", email: "jugend@ev-kirche-friedrichstadt.de", openingHours: "Di  9 bis 11 Uhr" },
  { id: 14, name: "Jugendfeuerwehr Friedrichstadt", category: "Jugendfeuerwehr", address: "Eiland 10  25840 Friedrichstadt", phone: "0 48 81 - 312", email: "jugendwart@feuerwehr-friedrichstadt.de" },
  { id: 15, name: "Friedrichstädter Turnverein", category: "Sportverein", address: "Friedrichstadt", phone: "04882-1068", email: "info@friedrichstaeter-turnverein.de" },
  { id: 16, name: "Die Krücke", category: "Familienberatung", address: "Kirchenstraße 14   Kirchenstraße 14", phone: "0174/6538035", email: "maike@die-kruecke.com" },
  { id: 17, name: "Jugendherberge Friedrichstadt", category: "Jugendherberge", address: "Ostdeutsche Str. 1, 25840 Friedrichstadt", phone: "04881 936261", email: "friedrichstadt@jugendherberge.de" },
  { id: 18, name: "Mobile Tafel", category: "Tafel", address: "Großer Garten", phone: "0175 7344236", email: "rolf.riemann@dw-husum.de", openingHours: "Dienstag 12:00 – 13:00 Uhr" },
  { id: 19, name: "Mobile Tafel", category: "Tafel", address: "auf dem Dörpsplatz", phone: "0175 7344236", email: "rolf.riemann@dw-husum.de", openingHours: "Dienstag 10:00 – 11:00 Uhr" },
  { id: 20, name: "Mobile Tafel", category: "Tafel", address: "am Kirchengemeinde-Haus", phone: "0175 7344236", email: "rolf.riemann@dw-husum.de", openingHours: "Donnerstag 12:00 – 13:00 Uhr" },
  { id: 21, name: "Mobile Tafel", category: "Tafel", address: "auf dem Parkplatz der Nord-Ostsee Sparkasse", phone: "0175 7344236", email: "rolf.riemann@dw-husum.de", openingHours: "Donnerstag 10:00 – 11:00 Uhr" },
  { id: 22, name: "Theodor-Mommsen-Schule", category: "Schule", address: "Marienstraße 14, 25836 Garding", phone: "04862 201725", email: "Theodor-Mommsen-Schule.Garding@schule.landsh.de" },
  { id: 23, name: "Theodor-Mommsen-Schule", category: "Schule", address: "Kirchendeich, 25881 Tetenbüll", phone: "04862 - 777", email: "Theodor-Mommsen-Schule.Garding@schule.landsh.de" },
  { id: 24, name: "Evangelische Kindertagesstätte St. Christian", category: "Kita", address: "Marienstraße 10  25836 Garding", phone: "+49 (4862) 8055", email: "kita-garding@ev-kita-werk.de" },
  { id: 25, name: "Dansk Boernehave Dänischer Kindergarten", category: "Kita", address: "Osterende 29, 25836 Garding Kirchspiel", phone: "04862 912" },
  { id: 26, name: "Jugendzentrum Garding", category: "Jugendzentrum", address: "Graureiherweg 4, 25836 Garding", phone: "04862/1046029", email: "u.happy@web.de" },
  { id: 27, name: "Gemeindepfadfinder Garding", category: "Freizeit", address: "Markt 4 25836 Garding", phone: "+49 4862 17267", email: "garding@regp.de" },
  { id: 28, name: "Kirchengemeinde St. Christian Garding Chor", category: "Freizeit", address: "Markt 4 25836 Garding", phone: "04862 17267", email: "kg@kirche-eiderstedt.de" },
  { id: 29, name: "Boßelverein Garding", category: "Sportverein", address: "Norderring 22, 25836 Garding", phone: "Vorstand  0160 983 155 23", email: "(Vorstand)  k.flor@flor.lvm.de" },
  { id: 30, name: "TSV Garding", category: "Sportverein", address: "Garding", phone: "Tel 04862388" },
  { id: 31, name: "KiWA Kinderwerkstatt Atelier", category: "Freizeit", address: "Kulturhaus Garding Enge Str. 5 (Hintereingang)", phone: "0163-9173357 Thomas Kuhn oder Förderverein für Kunst und Kultur Eiderstedt e.V. - Fon: +49.4862.2019975", email: "info@fke-eiderstedt.de", openingHours: "mittwochs von 15 – 17 Uhr Während der Schulferien ist das Atelier geschlossen" },
  { id: 32, name: "Musik für Garding e.V. Musikverein", category: "Freizeit", address: "25836 Garding, Nordergeestweg 26", email: "moin@musik-fuer-garding.de" },
  { id: 33, name: "Dr. med. Nathalie Beaud", category: "Kinderarzt", address: "Osterstraße 18, 25836 Garding", phone: "04862 206", email: "info@kinderarztpraxis-beaud.de", openingHours: "Mo Di Do Fr 08:00–12:00, 14:00–17:00 Mi 08:00–12:00" },
  { id: 34, name: "Reit- und Fahrverein Eiderstedt e.V.", category: "Freizeit", address: "Graureiherweg 13, Garding", phone: "04862 8702" },
  { id: 35, name: "Hobby Horsing Garding", category: "Freizeit", address: "Turnhalle des Dänischen Kindergartens. Osterende 29 25836 Garding", email: "jennysbriefkasten@hotmail.de", openingHours: "Jeden Samstag um 11 Uhr" },
  { id: 36, name: "Psychologisches Beratungszentrum Husum", category: "Psychologie", address: "Theodor-Storm-Straße 7 25813 Husum", phone: "04841 691440", email: "info@dw-husum.de", openingHours: "Mo bis Do 8 - 17 Uhr Fr 8 -13 Uhr Mi 14 -15.30 Uhr offene Sprechstunde" },
  { id: 37, name: "Kinderschutz-Zentrum Westküste\nHusum", category: "Kinderschutz-Zentrum", address: "Theodor-Storm-Straße 7 25813 Husum", phone: "04841 691450", email: "kinderschutz@dw-husum.de", openingHours: "Mo bis Do 8 - 17 Uhr Fr 8 -13 Uhr" },
  { id: 38, name: "Baumhaus Tagesklinik Husum", category: "Psychologie", address: "Theodor-Schäfer-Str. 1a 25813 Husum", phone: "(04841) 770-97620", openingHours: "Mo bis Do 8- 16.30 Uhr Fr 8- 14.30" },
  { id: 39, name: "Lebenshilfe Husum", category: "Lebenshilfe", address: "Soltbargen 5  25813 Husum", phone: "04841 98398 0", email: "verwaltung@lebenshilfe-husum.de" },
  { id: 40, name: "Käte-Reiners-Kindergarten (inkliusive Kita)", category: "Kita", address: "Schobüller Straße 42 25813 Husum", phone: "04841 98398-30", email: "lh-kita@lebenshilfe-husum.de", openingHours: "7-15 Uhr" },
  { id: 41, name: "EGH E Husum", category: "Eingliederungshilfe", address: "Marktstraße 6 25813 Husum", phone: "04841 67-758", email: "eghe@nordfriesland.de", openingHours: "Mo 8-12 Uhr Do 8-12 Uhr und 14-16 Uhr Fr  8-12 Uhr" },
  { id: 42, name: "Förderzentrum \nPestalozzi-Schule Husum", category: "Förderzentrum/ Schule", address: "Schobüller Straße 38 25813 Husum", phone: "0 48 41 666 8450", email: "pestalozzi-schule.husum@schule.landsh.de", openingHours: "Mo bis Fr 7.30-13.30 Uhr" },
  { id: 43, name: "Förderzentrum geistige Entwicklung Rungholtschule Husum", category: "Förderzentrum/ Schule", address: "Hermann-Tast-Str. 62 25813 Husum", phone: "04841 83640", email: "Rungholtschule.Husum@schule.landsh.de" },
  { id: 44, name: "Tischtennisverein Koldenbüttel", category: "Sportverein", address: "Achtern Holm 10 25878 Drage", email: "info@reet-riechmann.de", openingHours: "Dienstags und Freitags ab 19:00 Uhr in der Halle der ETS Friedrichstadt, Mittwochs ab 20:00 Uhr in der Halle der Grundschule Friedrichstadt." },
  { id: 45, name: "Naturerlebnisraum »Koldenbüttler Marsch«", category: "Freizeit", address: "Koldenbüttel" },
  { id: 46, name: "Baumpfad Koldenbüttel", category: "Freizeit", address: "Koldenbüttel" },
  { id: 47, name: "Ringreitergilde Koldenbüttel", category: "Sportverein", address: "Koldenbüttel", phone: "+49 173 9958 863" },
  { id: 48, name: "Freizeitkicker-Koldenbüttel (ab 14)", category: "Sportverein", address: "Sportplatz, Mühlenstraße", phone: "04881 8453 (Aktuell?)", openingHours: "Dienstags von 19:30 - 21:00 Uhr" },
  { id: 49, name: "Boß­el­ver­ein Kol­den­büt­tel", category: "Sportverein", address: "Koldenbüttler Sportplatz", email: "mark.schreiber@bv-koldenbuettel.de", openingHours: "Montags um 17:00 Uhr" },
  { id: 50, name: "Mars-Skipper-Hof Erlebnishof", category: "Freizeit", address: "Gardinger Chaussee 3 25832 Kotzenbüll", phone: "0 48 61 / 61 74 80", email: "info@eingartenfuerdiesinne.de", openingHours: "Nach Anmeldung" },
  { id: 51, name: "Boßelverein Kotzenbüll", category: "Sportverein", address: "Dorfstraße 1, 25832 Kotzenbüll" },
  { id: 52, name: "Privatschule Oldenswort", category: "Schule", address: "Königskampweg 1 25870 Oldenswort", phone: "04864 466", email: "schulleitung@privatschule-oldenswort.de" },
  { id: 53, name: "Kindertagesstätte Oldenswort", category: "Kita", address: "Königskampweg 1 25870 Oldenswort", phone: "04864 717", email: "kita@oldenswort.sh" },
  { id: 54, name: "Gemeindepfadfinder St. Pankratius Oldenswort", category: "Freizeit", address: "Osterender Chaussee 3 25870 Oldenswort", phone: "+49 4864 10181", email: "oldenswort@regp.de" },
  { id: 55, name: "Jugendclub ZACK", category: "Jugendclub", address: "Königskampweg 1 25870 Oldenswort" },
  { id: 56, name: "Boßelverein Oldenswort", category: "Sportverein", address: "Oldenswort", phone: "0170 – 3226822", email: "doertechristiansen@gmx.de" },
  { id: 57, name: "Ringreitergilde Oldenswort", category: "Sportverein", address: "Oldenswort", phone: "0160 91423845", email: "gilde.oldenswort@gmail.com" },
  { id: 58, name: "Jugendfeuerwehr Oldenswort", category: "Jugendfeuerwehr", address: "An de Schützenwarft 1, 25870 Oldenswort", phone: "0152-3634 56 86", email: "pm bei Instagramm https://www.instagram.com/jf_oldenswort/?hl=de", openingHours: "jeden zweiten Freitag von 18- 20 Uhr" },
  { id: 59, name: "TSV Oldenswort", category: "Sportverein", address: "Königskampweg 4 25870 Oldenswort", phone: "0172 – 6674271", email: "tsv-oldenswort@t-online.de" },
  { id: 60, name: "Kindergarten der Gemeinde Oldersbek", category: "Kita/Krippe", address: "Schulstraße 11 25873 Oldersbek", phone: "04848 / 9012571", email: "kiga-oldersbek@t-online.de" },
  { id: 61, name: "Jugendfeuerwehr Oldersbek    (mind 10 Jahre)", category: "Jugendfeuerwehr", address: "Ostergaard 17 25873 Oldersbek", phone: "04848 902411", email: "Feuerwehr-Oldersbek@t-online.de", openingHours: "alle 14 Tage donnerstags um 18:00 Uhr" },
  { id: 62, name: "TSV - Oldersbek", category: "Sportverein", address: "Grünthal 12  25873 Oldersbek", phone: "+494848 9039095", email: "Kati240489@t-online.de" },
  { id: 63, name: "Ringreiterverein \"Hol Di Fast Oldersbek\"", category: "Sportverein", address: "25873 Oldersbek", phone: "Laura Lorenzen" },
  { id: 64, name: "Otto-Thiesen-Schule", category: "Schule", address: "Süderweg 35 25872 Ostenfeld", phone: "+49 4845 378", email: "Otto-Thiesen-Schule.Ostenfeld@schule.landsh.de", openingHours: "Mo bis Do 8 - 13 Uhr Fr 8 -11.15 Uhr" },
  { id: 65, name: "Ev. Kindertagesstätte Ostenfeld (Mit Waldgruppe)", category: "Kita/Krippe", address: "Schwarzen Weg 12, Ostenfeld", phone: "04845 / 1480", email: "kita-ostenfeld@ev-kita-werk.de", openingHours: "montags bis freitags von 7 bis 17 Uhr" },
  { id: 66, name: "Mädchentreff Ostenfeld (mit Nachmittagsbetreuung)", category: "Jugendtreff Mädchentreff", address: "Süderweg 35 25872 Ostenfeld", phone: "174/9904725", email: "teamostenfeld@t-online.de" },
  { id: 67, name: "Team Ostenfeld \"Die Flotten Lotten\"", category: "Freizeit", address: "Süderweg 35 25872 Ostenfeld", phone: "+49 4845 7906140", email: "teamostenfeld@t-online.de" },
  { id: 68, name: "Jugendfeuerwehr Ostenfeld (auch Wittbek und Winnert)", category: "Jugendfeuerwehr", address: "Winnerter Straße 1 25872 Ostenfeld", phone: "04845-790166", email: "guido.feddersen@feuerwehr-ostenfeld.de", openingHours: "jeder zweite und vierte Mittwoch 18.30 am Gerätehaus" },
  { id: 69, name: "HSG Sportzentrum Ostenfeld (Handball)", category: "Sportverein", address: "Ostenfeld", email: "via Website: https://hsg-szoww.de/kontakt/" },
  { id: 70, name: "TSV Ostenfeld (Badminton, Breitensport, Handball, Sportschießen, Turnen)", category: "Sportverein", address: "Ostenfeld", phone: "0171-5374091", email: "tsv.petersen@t-online.de" },
  { id: 71, name: "Feuerwehrmusikzug Ostenfeld/Schwabstedt", category: "Musikverein", address: "Feuerwehrgerätehaus in Ostenfeld", phone: "04845-1593", openingHours: "jeden Donnerstag um 19.30 Uhr" },
  { id: 72, name: "Ev. Bläsergemeinschaft Ostenfelde", category: "Musikverein", address: "Friedenskapelle in Ostenfelde", phone: "02524 / 2338", email: "anne.esselmann1@ekvw.de", openingHours: "jeden Mittwoch von 19.00 - 20.30 Uhr" },
  { id: 73, name: "Freibad Ostenfeld", category: "Freizeit", address: "Torenstoff, 25872 Ostenfeld", phone: "(0 48 45) 15 63", email: "INFO@Freibad-Ostenfeld.de" },
  { id: 74, name: "Konfirmationsunterricht \nEv.-Luth. Kirchengemeinde Ostenfeld", category: "Kirche", address: "Hauptstraße 19 25872 Ostenfeld", phone: "04845 / 348", email: "kirchenbuero@kirche-ostenfeld.de" },
  { id: 75, name: "Boßelverein Heverbund", category: "Sportverein", address: "Osterhever", email: "info@bv-spo.de" },
  { id: 76, name: "Ringreiterverein Osterhever e.V.", category: "Sportverein", address: "Osterhever", phone: "04865 387", email: "heike.voss81@gmail.com" },
  { id: 77, name: "Kinderstube Heverbund  (Vorkindergartenalter)", category: "Freizeit", address: "Pfarrhaus von Osterhever", phone: "0173 1552648", openingHours: "Dienstag und Donnerstag von 9:00 - 11:00 Uhr" },
  { id: 78, name: "Fruunsboßelvereen Eiderbund e.V", category: "Sportverein", address: "Welt", email: "eiderbundfrauen@gmail.com" },
  { id: 79, name: "SV Ramstedt", category: "Sportverein", address: "Ramstedt", phone: "04884/631", email: "Kontakt via Website: https://www.svramstedt.de/Kontakt.php" },
  { id: 80, name: "Grundschule Rantrum", category: "Schule", address: "Bannony 2 25873 Rantrum", phone: "04848 850", email: "grundschule.rantrum@schule.landsh.de" },
  { id: 81, name: "DRK-Kindergarten Rantrum", category: "Kita", address: "Raiffeisenstr. 10 25873 Rantrum", phone: "04848 / 903927-0", email: "info@kigarantrum.de" },
  { id: 82, name: "Jugendtreff Rantrum", category: "Jugendtreff", address: "Alte Schule Rantrum", openingHours: "Mo und Do 15 -18 Uhr" },
  { id: 83, name: "Jugendfeuerwehr Rantrum", category: "Jugendfeuerwehr", address: "Alte Dorfstraße 22 25873 Rantrum", phone: "04848 535", email: "info@feuerwehr-rantrum.de" },
  { id: 84, name: "Freibad Rantrum", category: "Freibad", address: "Sportplatz 19, 25873 Rantrum", phone: "04848 901624", email: "info@freibad-rantrum.de" },
  { id: 85, name: "TSV Rantrum", category: "Sportverein", address: "Bannony 3, 25873 Rantrum", email: "Kontakt via Website: https://www.tsv-rantrum.de/" },
  { id: 86, name: "Praxis für Logopädie Joana Böttcher", category: "Logopädie", address: "25873 Rantrum Husumer Straße 1", phone: "0 48 48  – 90 38 873", email: "mail-logopaedie-rantrum@gmx.de" },
  { id: 87, name: "Lütt Dörp School Grundschule Schwabstedt", category: "Schule", address: "Westerende 32, 25876 Schwabstedt", phone: "04884 529", email: "luett-doerp-school.schwabstedt@schule.landsh.de" },
  { id: 88, name: "Kindergarten \"Zwergenland\" Schwabstedt", category: "Kita", address: "An der Treene (Treenehaus) 11 25876 Schwabstedt", phone: "04884 / 909489-0", email: "info@kiga-schwabstedt.de" },
  { id: 89, name: "Jugendtreff Schwabstedt", category: "Jugendtreff", address: "Schwabstedt", email: "jugendbetreuung@gemeinde-schwabstedt.de" },
  { id: 90, name: "FASV Schwabstedt", category: "Freizeit", address: "Westen de Kark 55, 25872 Ostenfeld", phone: "04845 - 790854", email: "1.vorsitzender@fasv-schwabstedt.de" },
  { id: 91, name: "Jugendfeuerwehr Schwabstedt", category: "Jugendfeuerwehr", address: "Westerende 30b 25876 Schwabstedt", phone: "0151-50672443", email: "jugendwart@feuerwehr-schwabstedt.org" },
  { id: 92, name: "Sprachcafe Schwabstedt", category: "Sprache", address: "Alte Dorfstraße 9 25876 Schwabstedt", phone: "4884 201", email: "schwabstedt@kirche-nf.de" },
  { id: 93, name: "St. Jakobi Kirchengemeinde  Konfirmationsunterricht", category: "Kirche", address: "Alte Dorfstraße 9 25876 Schwabstedt", phone: "4884 201", email: "schwabstedt@kirche-nf.de" },
  { id: 94, name: "Dr. Wacker Allgemeinmediziner", category: "Arzt", address: "Westerende 13 25678 Schwabstedt", phone: "04884/ 218", email: "praxis@hausarzt-schwabstedt.de" },
  { id: 95, name: "Ortskulturring Schwabstedt (mit Angeboten für Kinder und Jugendliche)", category: "Verein", address: "Schwabstedt", phone: "04884 1013" },
  { id: 96, name: "MTV Schwabstedt", category: "Sportverein", address: "TRASSENHEIDER WEG 1, 25876 SCHWABSTEDT", phone: "4884/9091946", email: "mtv10@web.de" },
  { id: 97, name: "Jugendfeuerwehr Seeth", category: "Jugendfeuerwehr", address: "Schulring 2, 25878 Seeth", phone: "0173 2461821", email: "wehrfuehrer@feuerwehr-seeth.de", openingHours: "alle 2 Wochen freitags von 17:30Uhr – 19:30Uhr" },
  { id: 98, name: "Ev. Kindergarten Simonsberg", category: "Kita", address: "Hauptstraße 18 25813 Simonsberg", phone: "+49 4841 3408", email: "simonsberg@kirchenkreis-husum.de" },
  { id: 99, name: "Boßelverein Simonsberg von 1889 e. V", category: "Sportverein", address: "Simonsberg", phone: "0173 3285495 (Männer Verein) 0176 3863822 (Frauen Verein)" },
  { id: 100, name: "Jugendfeuerwehr Simonsberg", category: "Jugendfeuerwehr", address: "Dorfstraße 1 25813 Simonsberg", phone: "0152 21877834", email: "F.Feuerwehr1908@gmail.com" },
  { id: 101, name: "Nordsee-Internat", category: "Schule", address: "Pestalozzistraße 72 25826 St. Peter-Ording", phone: "04863 47 11 0", email: "info@nsi-spo.de" },
  { id: 102, name: "Nordseeschule Gymnasium", category: "Schule", address: "Pestalozzistr. 62-70 25826 St. Peter-Ording", phone: "04863-47550", email: "Nordseeschule.St.Peter-Ording@Schule.LandSH.de", openingHours: "Nordseeschule.St.Peter-Ording@Schule.LandSH.de" },
  { id: 103, name: "Nordseeschule Gemeinschaftsschulteil", category: "Schule", address: "Fasanenweg 5 25826 St. Peter-Ording", phone: "04863-9150", email: "Nordseeschule-Gemeinschaftsschulteil.St.Peter-Ording@schule.landsh.de" },
  { id: 104, name: "Utholm-Schule Grundschule  (mit DAZ Zentrum)", category: "Schule", address: "Kirchenleye 7 25826 St. Peter-Ording", phone: "04863 - 9146", email: "Utholm-Schule.St.Peter-Ording@schule.landsh.de" },
  { id: 105, name: "Ev. Kindertagesstätte und Familienzentrum St. Peter-Ording", category: "Kita", address: "Kirchenleye 8 25826 St.Peter-Ording", phone: "+49 4863 99895-0", email: "buero@kirche-spot.de" },
  { id: 106, name: "JOS Jugendzentrum", category: "Jugendtreff", address: "Pestalozzistraße 62 25826 St.Peter-Ording", phone: "04863 – 9508018", email: "Jos-Spo@gmx.de" },
  { id: 107, name: "Dünen-Therme", category: "Freibad", address: "Maleens Knoll 2, 25826 St. Peter-Ording", phone: "048639990", email: "info@duenen-therme.de" },
  { id: 108, name: "Erlebnis-Hus", category: "Freizeit", address: "Fritz-Wischer-Str. 1 25826 St. Peter-Ording", phone: "48639990", email: "info@tz-spo.de" },
  { id: 109, name: "Westküstenpark & Robbarium", category: "Freizeit", address: "Wohldweg 6 - 25826 St. Peter-Ording", phone: "04863-3044", email: "info@westkuestenpark.de" },
  { id: 110, name: "Nationalpark-Haus Sankt Peter-Ording", category: "Freizeit", address: "Maleens Knoll 2, Sankt Peter-Ording", phone: "04863/9504254", email: "st-peter-ording@schutzstation-wattenmeer.de" },
  { id: 111, name: "Familienzentrum St. Peter-Ording (Elterncafe, Beratung, Interkulturelle Begegnung, Kinderbewegung, Eltern-Kind Kurs, Logo, Ergo, Physio)", category: "Familienzentrum", address: "Olsdorferstraße 19 25826 St. Peter-Ording", phone: "04863 4786750", email: "ev-familienzentrum-spo@ev-kita-werk.de" },
  { id: 112, name: "Landjugend Tating", category: "Freizeit", address: "Düsternbrook \"Alte Schule\" 25881 Tating", email: "laju-tating@gmx.de", openingHours: "Jeden Donnerstag oder Freitag ab 20 Uhr" },
  { id: 113, name: "Boßelverein Tating", category: "Sportverein", address: "Tating", phone: "0175 9066843", email: "kontakt@bv-tating.de" },
  { id: 114, name: "Turn- und Spielverein Tating", category: "Sportverein", address: "Düsternbrook 6-8 25881 Tating", phone: "0171-1079636", email: "info@tus-tating.de" },
  { id: 115, name: "Ev. Kindertagesstätte Tetenbüll", category: "Kita", address: "Kirchdeich 1 25882 Tetenbüll", phone: "04862-1046111", email: "kindergarten.tetenbuell@kirche-eiderstedt.de" },
  { id: 116, name: "Theodor-Mommsen-Schule", category: "Schule", address: "Kirchendeich, 25881 Tetenbüll", phone: "04862 - 777", email: "Theodor-Mommsen-Schule.Garding@schule.landsh.de" },
  { id: 117, name: "Erlebnisbauernhof Kantorhof", category: "Freizeit", address: "Kantorsweg 6 25882 Tetenbüll", phone: "0162 9479552", email: "post@kantorhof-urlaub.de" },
  { id: 118, name: "Boßelverein Tetenbüll", category: "Sportverein", address: "Tetenbüll", email: "simon.rohde@bv-tetenbuell.de" },
  { id: 119, name: "TSV Tetenbüll", category: "Sportverein", address: "Süderenn 5 25882 Tetenbüll", phone: "+49 151 6143 7549", email: "witte.tetenbuell@freenet.de" },
  { id: 120, name: "Jugendfeuerwehr Tetenbüll", category: "Jugendfeuerwehr", address: "Westerenn 2 25882 Tetenbüll", email: "st.kroening@web.de" },
  { id: 121, name: "Ev.-Luth. Kirchengemeinde Tetenbüll/Katharinenheerd (Musik, Konfirmantenunterricht)", category: "Kirche", address: "Tetenbüll", phone: "+49 4862 1590", email: "tetenbuell@kirche-eiderstedt.de" },
  { id: 122, name: "Ringreitverein Tetenbüll", category: "Sportverein", address: "Tetenbüll", email: "torgehansen@hotmail.de" },
  { id: 123, name: "Schule am Ostertor", category: "Schule", address: "Hochsteg 26 25832 Tönning", phone: "04861 / 96800", email: "schule-am-ostertor.toenning@schule.landsh.de" },
  { id: 124, name: "Eider Treene Schule Tönning", category: "Schule", address: "Badallee 14 25832 Tönning", phone: "04861-61000", email: "eider-treene-schule.toenning@schule.landsh.de" },
  { id: 125, name: "Uffe-Skolen Grund- und Gemeinschaftsschule", category: "Schule", address: "Herzog-Philipp-Allee 3a 25832 Tönning", phone: "+49 4861236", email: "uffe-skolen@skoleforeningen.org" },
  { id: 126, name: "Städtischer Kindergarten Tönning", category: "Kita", address: "Rieper Weg 10A, 25832 Tönning", phone: "+49 4861 5496", email: "leitungsteam@kita-toenning.de" },
  { id: 127, name: "ADS-Kita Tönning", category: "Kita", address: "Hugo-Buschmann-Str. 52 25832 Tönning", phone: "04 86 1 - 55 06", email: "ads-kita-hugo-buschmann-strasse@dein-ads.de" },
  { id: 128, name: "Dänischer Kindergarten Tønning Børnehave", category: "Kita", address: "Herzog-Philipp-Allee 3a  25832 Tönning", phone: "0 48 61 / 54 08" },
  { id: 129, name: "Integrativer Kindergarten Nis-Puk e.V.", category: "Kita", address: "Esmarchstraße  4 25832 Tönning", phone: "0 48 61 / 67 14", email: "info@nis-puk-kindergarten.de" },
  { id: 130, name: "Jugendzentrum Tönning", category: "Jugendtreff", address: "Strandweg 1,25832 Tönning", phone: "04861-5531", email: "jugendzentrum@toenning.de", openingHours: "Montags - Freitags von 12:00 Uhr - 18:00 Uhr" },
  { id: 131, name: "Familienzentrum Tönning", category: "Familienzentrum", address: "Osterender Chaussee 3 | 25870 Oldenswort", phone: "0160-5012986", email: "familienzentrum-toenning@dw-husum.de" },
  { id: 132, name: "Psychologisches Beratungszentrum Tönning", category: "Psychologie", address: "Johann-​Adolf-Straße 7/9 25832 Tönning", phone: "04841 691440", email: "pbz@dw-husum.de" },
  { id: 133, name: "Tönning Außenstelle des Kinderschutz Zentrum Husum", category: "Kinderschutz-Zentrum", address: "Tönning", phone: "04841 691450", email: "kinderschutz@dw-husum.de" },
  { id: 134, name: "TSV Tönning", category: "Sportverein", address: "Friedrichstädter Chaussee 25832 Tönning", phone: "0172 8096995", email: "toenningersv@web.de" },
  { id: 135, name: "Psychomotorisches Turnen für Kleinkinder", category: "Psychomotorik", address: "Turnhalle der Uffe Skolen (Dänische Schule), Tönning", phone: "0170  8888180", openingHours: "montags 16:00 bis 17:00 Uhr keine Anmeldung nötig" },
  { id: 136, name: "Ergotherapiepraxis Ellin Schulze", category: "Ergotherapie", address: "Festungstr. 52    25832 Tönning", phone: "04861 690699", email: "ergo-toenning@t-online.de" },
  { id: 137, name: "SPRECHSTÜNN Praxen für Logopädie", category: "Logopädie", address: "Neustraße 1, 25832 Tönning", phone: "04841-663 2234  und  0174 2469667", email: "info@logo-sprechstuenn.de" },
  { id: 138, name: "IF Tönning Fußballverein", category: "Sportverein", address: "Sportplatz an der Dänischen Schule Herzog-Philipp-Allee 3 a", phone: "04861 - 385" },
  { id: 139, name: "Jugendfeuerwehr Tönning", category: "Jugendfeuerwehr", address: "Dithmarscher Straße 11  25832 Tönning", phone: "0 48 61 / 61 07 66", email: "wf@feuerwehr-toenning.de", openingHours: "Freitags um 17:00 Uhr" },
  { id: 140, name: "Multimar Wattforum", category: "Freizeit", address: "Dithmarscher Str. 6a, 25832 Tönning", phone: "0 48 61 96 200", email: "info@multimar-wattforum.de" },
  { id: 141, name: "Die THW Jugend Tönning", category: "Freizeit", address: "Dithmarscherstr. 13  25832 Tönning", phone: "+49 4861-5665", email: "ov-toenning@thw.de", openingHours: "Kontakt via Website https://ov-toenning.thw.de/kontakt/jugend?type=c" },
  { id: 142, name: "Ev.-Luth. Kirchengemeinde Tönning-Kating-Kotzenbüll (Chor, Instrumente, Konfi)", category: "Kirche", address: "Johann-Adolf-Straße 4, 25832 Tönning", phone: "04861/382", email: "toenning@kirche-eiderstedt.de" },
  { id: 143, name: "Freibad Tönning", category: "Freizeit", address: "Strandweg 2   25832 Tönning", phone: "0 48 61 - 56 88", email: "info@toenningtourismus.de" },
  { id: 144, name: "Stadtbücherei Tönning", category: "Freizeit", address: "Markt 1    2 58 32 Tönning", phone: "0 48 61 / 6 14 - 4 50", email: "buecherei@toenning.de", openingHours: "Mo, Di, Do, Fr   9-12 und  14-17.30  Sa 10-12" },
  { id: 145, name: "Fachstelle Migration Eiderstedt", category: "Migration", address: "Johann-Adolf-Straße 7 – 9     25832 Tönning", phone: "04841 9811330", email: "migration-eiderstedt@dw-husum.de", openingHours: "Di bis Fr 10 - 12 Uhr und Do 13 -  15 Uhr" },
  { id: 146, name: "Tönninger Tafel", category: "Tafel", address: "Johann-Adolf-Straße 7-9  25832 Tönning", phone: "+49 (4841) 691410", openingHours: "dienstags und freitags ab 11 Uhr" },
  { id: 147, name: "Landjugend Evershop (ab 14)", category: "Freizeit", address: "Uelvesbüll", email: "laju.evershop@gmx.de" },
  { id: 148, name: "Jugendfeuerwehr Roter Haubarg", category: "Jugendfeuerwehr", address: "Kirchspielplatz 2a 25889 Uelvesbüll", phone: "0151/70400221", email: "janpetersen2@freenet.de", openingHours: "Sommer jeden Mittwoch und im Winter alle 14 Tage" },
  { id: 149, name: "Boßelverein Uelvesbüll", category: "Sportverein", address: "Uelvesbüll", email: "karstenlamp@gmx.de" },
  { id: 150, name: "Ringreitervereinigung Uelvesbüll", category: "Sportverein", address: "Uelvesbüll", phone: "04864 - 100536", email: "martinadircks@hotmail.de" },
  { id: 151, name: "Angelverein Wehlenkieker e.V.", category: "Freizeit", address: "Uelvesbüll", phone: "04864/2717576", email: "diekstrom@web.de" },
  { id: 152, name: "Hof Frowähr ( Bauernhofpädagogik)", category: "Freizeit", address: "Frowähr 9, 25876 Wisch", phone: "04884-8699965", email: "info@hof-frowaehr.de" },
  { id: 153, name: "Ev. Kindergarten Wittbek", category: "Kita", address: "Knickweg 2 25872 Wittbek", phone: "04845 / 7464", email: "kita-ostenfeld@ev-kita-werk.de" },
  { id: 154, name: "FC Wittbek", category: "Sportverein", address: "Norderweg 1 25872 Wittbek", phone: "0171 - 7519339", email: "1.fc-wittbek@web.de" },
  { id: 155, name: "Kindergilde Wittbek \n1976 e.V.", category: "Freizeit/ Veranstaltungen", address: "Wittbek", email: "dejensens@t-online.de" },
  { id: 156, name: "\"Lütt Dörp School\" Grundschule Witzwort", category: "Schule", address: "Kirchenweg 2, 25889 Witzwort", phone: "04864 684", email: "luett-doerp-school.witzwort@schule.landsh.de" },
  { id: 157, name: "Ev. Kindertagesstätte Sonnenblume Witzwort", category: "Kita", address: "Kirchenweg 2, 25889 Witzwort", phone: "04864/1580", email: "kita-sonnenblume-witzwort@ev-kita-werk.de", openingHours: "Montags - Freitag von 06.30 Uhr - 17.00 Uhr" },
  { id: 158, name: "Jugendfeuerwehr Witzwort Roter Haubarg", category: "Jugendfeuerwehr", address: "Dorfstraße 33a  25889 Witzwort", phone: "01 70 / 40 38 354", email: "info@feuerwehr-witzwort.de", openingHours: "Jeden Mittwoch von 17 Uhr bis 19:30 Uhr" },
  { id: 159, name: "Tennisclub Witzwort", category: "Sportverein", address: "Margarete-Peters-Weg 9    25889 Witzwort", phone: "04864-303", email: "info@tcwitzwort.de" },
  { id: 160, name: "TSV Witzwort (mit Elternkindturnen und Kinderturnen)", category: "Sportverein", address: "Witzwort", phone: "48649409930", email: "tsvwitzwort@gmail.com" },
  { id: 161, name: "Ringreitverein Witzwort", category: "Sportverein", address: "Witzwort", email: "katja.greve@gmx.de" },
  { id: 162, name: "Kinderzentrum Pelzerhaken  Sozialpädiatrisches Zentrum/Fachklinik", category: "Sozialpädiatrie", address: "Zum Leuchtturm 4 23730 Neustadt in Holstein", phone: "+49 4561 71090", email: "rezeption@kinderzentrum-pelzerhaken.de" },
  { id: 163, name: "Werner Otto Institut  Sozialpädiatrisches Zentrum", category: "Sozialpädiatrie", address: "Bodelschwinghstr. 23 22337 Hamburg", phone: "040 50 77 02", email: "spz@werner-otto-institut.de" },
  { id: 164, name: "Ankerland e.V. Hamburg", category: "Traumabewältigung", address: "Löwenstraße 60       20251 Hamburg", phone: "Trauma-Therapie­zentrum: 040 - 46 86 396 - 0       Trauma-Info-Telefon: 040 – 6364 3627          Beratungs­zentrum:  040 – 46 86 396 – 14", email: "Trauma-Therapie­zentrum: ttz@ankerland.de        Beratungs­zentrum:  beratung@ankerland.de" },
  { id: 165, name: "Sozialpädiatrisches Zentrum Kiel", category: "Sozialpädiatrie", address: "Arnold-Heller-Str. 3 24105 Kiel Haus C - Eltern-Kind-Zentrum", phone: "0431 500-24151", email: "spz-kiel@uksh.de" },
  { id: 166, name: "Sozialpädiatrischen Zentrums (SPZ) Klinikum Itzehoe", category: "Sozialpädiatrie", address: "Robert-Koch-Straße 2  25524 Itzehoe", phone: "+49 4821 772-2228", email: "spz@kh-itzehoe.de" },
  { id: 167, name: "Der Bunte Kreis Nord (WKK) Unterstützung schwerkranker Kinder/ deren Familien", category: "sozialmedizinische Nachsorge", address: "Esmarchstraße 50 25746 Heide", phone: "0481 785-4284/4287", email: "bunterkreisnord@wkk-hei.de" },
  { id: 168, name: "Heilpädagogischer Dienst Flensburg", category: "Heilpädagogik", address: "Querstraße 5 24939 Flensburg", phone: "0461 / 48 170 20", email: "verwaltung@shd-flensburg.de" },
  { id: 169, name: "Landesförderzentrum Sehen, Schleswig", category: "Förderzentrum (Sehen)", address: "Lutherstraße 14   24837 Schleswig", phone: "04621-807-5", email: "lfs-schleswig@schule.landsh.de" },
  { id: 170, name: "Landesförderzentrum Autistisches Verhalten", category: "Förderzentrum (Autismus)", address: "Schreberweg 5, 24119 Kronshagen", phone: ": 0431 5403-196", email: "lfz-autistisches-verhalten.kronshagen@schule.landsh.de" },
  { id: 171, name: "Pflegestützpunkt im Kreis Nordfriesland", category: "Pflege Beratung", address: "Damm 8     25813 Husum", phone: "04841 67-710", email: "pflegestuetzpunkt@nordfriesland.de" },
  { id: 172, name: "Ole  School  Urlaubsangebote für Menschen mit Behinderung", category: "Freizeit", address: "Süden 2  25845 Nordstrand", phone: "1623404947", email: "karen-brauer@t-online.de" },
  { id: 173, name: "Landesförderzentrum Hören und Kommunikation", category: "Förderzentrum (hören)", address: "Lutherstraße 14, 24837 Schleswig", phone: "(04621) 80 70", email: "LFZ-HuK@schule.landsh.de" },
  { id: 174, name: "Hofkindergarten Backensholz", category: "Kita", address: "Schwabstedter Damm 10 25885 Oster-Ohrstedt", phone: "0152 – 54 62 65 04", email: "kinder@backensholz.de" },
];

export const categories = [...new Set(offers.map(o => o.category).filter(Boolean))].sort() as string[];

// Simple fuzzy + substring search across name/category/address/description
export function searchOffers(query: string, category?: string, limit = 10): OfferEntry[] {
  const q = (query || "").toLowerCase().trim();
  const cat = category?.toLowerCase().trim();

  const scored = offers
    .filter(o => !cat || cat === "alle" || o.category?.toLowerCase() === cat)
    .map(o => {
      const hay = [o.name, o.category, o.address, o.description].filter(Boolean).join(" ").toLowerCase();
      if (!q) return { o, score: 1 };
      if (hay.includes(q)) return { o, score: 3 };
      const qWords = q.split(/\s+/).filter(Boolean);
      let matches = 0;
      for (const w of qWords) if (w.length > 2 && hay.includes(w)) matches++;
      return { o, score: matches / Math.max(qWords.length, 1) };
    })
    .filter(s => s.score > 0.2)
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
    .map(s => s.o);

  return scored;
}
